server.config.strict_validation.enabled=false
internal.dbms.tx_log.fail_on_corrupted_log_files=false

dbms.security.procedures.unrestricted=apoc.*

server.memory.pagecache.size=512M

server.default_listen_address=0.0.0.0
server.directories.logs=/logs
